# @package _group_
data_root_dir: /home/wit627/ccshao/CFGAN/celeba-hq-dataset/
out_root_dir: /home/wit627/ccshao/CFGAN/experiments/
tb_dir: /home/wit627/ccshao/CFGAN/tb_logs/
pretrained_models: /home/wit627/ccshao/CFGAN/
